install: gradle wrapper --gradle-version 5.4.1
language: java
jdk:
  - oraclejdk9
before_script:
  - chmod +x gradlew
script:
  - ./gradlew check
  - ./gradlew codeCoverageReport
after_success:
  - bash <(curl -s https://codecov.io/bash)